export const THEMES = [
  'Nostalgia',
  'The Ocean at Night',
  'Controlled Chaos',
  'Something Yellow',
  'A Feeling You Can\'t Name',
  'Rebirth',
  'The Last Day of Summer',
  'Invisible Forces',
  'Underground',
  'Fever Dream',
  'Static',
  'Something That Used to Scare You',
  'The Space Between Seconds',
  'Loud Silence',
  'Overgrowth',
  'A Memory You Made Up',
  'The Weight of Small Things',
  'Fracture',
  'Horizon',
  'Raw',
  'The Color of Music',
  'Something Borrowed',
  'In Transit',
  'After the Storm',
  'Things Left Unfinished',
];
